apiVersion: v1
kind: Service
metadata:
  name: test-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
---
kind: Endpoints
apiVersion: v1
metadata:
  name: test-svc
subsets:
  - addresses:
      - ip: 45.54.44.102
    ports:
      - port: 80
        name: http
        protocol: TCP
      - port: 443
        name: https
        protocol: TCP
