apiVersion: v1
kind: Service
metadata:
  name: hello-headless-CLUSTERNAME
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: web
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
  clusterIP: None
