apiVersion: v1
kind: Service
metadata:
  name: hello-clusterip-CLUSTERNAME
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
